### ISSUE TITLE
Oanda v10 or v20?

### ISSUE THREAD

**Issue by haimivan** [elowy01/FOREX#1]
Hi,

is this project also for Oanda v20?

Thanks in advance!

**Comment by haimivan** [comment]
Hi,

it seems to be v10, as I can find 

    oanda=OandaAPI(url='https://api-fxtrade.oanda.com/v1/candles?',instrument='EUR_USD',granularity='H8',alignmentTimezone='Europe/London',dailyAlignment=22,start='2016-10-24T22:00:00',count=1)

 in `main.py` and this url should be oanda v10.

**Comment by elowy01** [comment]
Yes, you are right, this is for v1. I wrote this API before OANDA modified this url
